CREATE TABLE IF NOT EXISTS electricity_consumption (
    ID SERIAL PRIMARY KEY,
    APPLIANCE_NAME VARCHAR(50) NOT NULL,
    POWER_CONSUMPTION_VAL SMALLINT NOT NULL, 
    RECORDED_AT_TIMESTAMP TIMESTAMP NOT NULL
);

